<a href="https://colab.research.google.com/github/adi2003/Aditya-Kumar-CodingWeek/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Tensors

In [3]:
#import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [5]:
#create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [7]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check the dimensions of the vector
vector.ndim

1

In [11]:
#create a matrix(has more than one dimensions)
matrix=tf.constant([[7,10],[10,7],[3,3]])
matrix


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7],
       [ 3,  3]], dtype=int32)>

In [12]:
matrix.ndim

2

Notice that the number of elements in the shape attribute of the tensor seems to be the number the dimensions

In [17]:
#dtype parameter
another_matrix=tf.constant([[10,7],[7,10]],dtype=tf.float32) ## specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

In [18]:
another_matrix.ndim

2

In [21]:
#lets create a tensor with 3 dimensions #a tensor has more than 2 dimensions
tensor1=tf.constant([[[10,20],[5,3]],[[1,2],[7,9]],[[1,3],[9,9]]])
tensor1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[10, 20],
        [ 5,  3]],

       [[ 1,  2],
        [ 7,  9]],

       [[ 1,  3],
        [ 9,  9]]], dtype=int32)>

In [20]:
tensor1.ndim

3

What we have learned so far
* Scalar
* vector
* matrix
* tensor
* tf.constant()
* ndim
* dtype

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.


In [ ]:
#creating tensors with variable
#A variable maintains shared, persistent state manipulated by a program.


In [22]:
#create the same tensor with tf.variable() as above
#might be changable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [27]:
#Let's try change one of the elements in our changeable tensor
changeable_tensor[0].assign(0)
changeable_tensor.assign([-100,100])
changeable_tensor

#changeable tensor can be changed using the assign statement(because we created using the tf.variable())
#unchangeable tensor was created when we made it using the tf.constant()



<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-100,  100], dtype=int32)>